### ISSUE TITLE
Route Page - Display bug on Firefox 45.0.1 // Win 7 Enterprise SP1

### ISSUE THREAD

**Issue by Galven** [zugspitze/Hiking-Buddies#12] opened 2018-06-27 18:27 UTC
Route page - I zoomed out just to be able to show everything, but that's the same if I have the normal 100% zoom

Example with https://www.hiking-buddies.com/routes/routes_list/149/

![1](https://user-images.githubusercontent.com/40529268/41992348-bc108fd0-7a37-11e8-85f0-bd83d27b41aa.JPG)
![2](https://user-images.githubusercontent.com/40529268/41992349-bc2b37ea-7a37-11e8-99f0-963f43b0f8d3.JPG)
![3](https://user-images.githubusercontent.com/40529268/41992350-bc489d3a-7a37-11e8-92f5-4bb6d3df1b23.jpg)

**Comment by zugspitze** [comment] 2018-06-27 18:39
@Galven Are you able to zoom in? What happens when you zoom in?

**Comment by Galven** [comment] 2018-06-27 18:45
![1](https://user-images.githubusercontent.com/40529268/41993213-3228b114-7a3a-11e8-8a95-9875e1cbabb8.JPG)
![2](https://user-images.githubusercontent.com/40529268/41993216-349dfc74-7a3a-11e8-901b-7fca55f04032.JPG)

**Comment by Galven** [comment] 2018-06-29 15:31
Looks like it's been fixed. You did something ?

**Comment by zugspitze** [comment] 2018-06-29 16:11
No, I didn't change anything. I don't have windows, so I was waiting for my friend to test it for me (he is on vacation). If you can't reproduce it anymore, please close the issue.

**Closed as completed** 2018-06-29 16:13 UTC
Labels: bug, UI/UX design
